apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: todo-db-daily
  namespace: default
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: todo-db
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: n8n-db-daily
  namespace: default
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: n8n-db
